### ISSUE TITLE
Allow bot developers to private their listings.

### ISSUE THREAD

**Issue by poutingemoji** [top-gg/issues#767] opened 2021-07-26 15:49 UTC
Feature: Allow bot developers to private their listings.

#### Suggestion

I think we should allow developers to private their listings because it provides a better experience for the user and the developer. Whether I don't want my bot advertised while I'm reworking it, because I don't work on the bot anymore, or because I don't want to host the bot temporarily while its not getting enough traffic, the only option shouldn't be just deleting the listing. I know I for one would greatly appreciate this feature.

#### Applicable Links or Attachments

A checkbox for "private" when editing a bot's listing.

**Comment by Xetera** [comment] 2021-07-26 15:50
Duplicate of #761

**Comment by poutingemoji** [comment] 2021-07-26 15:51
Yeah mb, I just saw that

**Closed by Xetera** 2021-07-26 15:50 UTC
