### ISSUE TITLE
Being able to choose a channel where DSL will create an invite

### ISSUE THREAD

**Issue by jotapedroefe** [top-gg/issues#445] opened 2020-10-27 16:04 UTC
Well the tittle explains it all, we could get an option to choose on the interface where the bot would create the invite for the server, right now it is creating on a random channel one of my private logging channels and i would like to have a invite by the bot online so it gets on our tracking invites bot.

Thanks :)

**Comment by Xignotic84** [comment] 2020-10-28 00:41
Duplicate of #195

**Closed by Xignotic84** 2020-10-28 00:41 UTC
