### ISSUE TITLE
Can't vote

### ISSUE THREAD

**Issue by Raffa50** [top-gg/issues#799] opened 2021-09-07 08:40 UTC
#### Expected Behavior

When I go to vote and press vote, my vote is assigned

#### Observed Behavior

I press vote, try again button appears, I press and still not working

#### Applicable Links or Attachments

!![image](https://user-images.githubusercontent.com/514534/132313339-55771160-00a6-48e5-a6f3-3e2c984815be.png)
https://top.gg/bot/550613223733329920/vote

#### Steps to Reproduce

1. Open https://top.gg/bot/550613223733329920/vote
2. Wait ad
3. Press vote

#### Web Browser and Version

Brave 1.29.77
Edge 93.0.961.38

#### Operating System and Version

Windows 10 Pro

#### Screen Resolution

1920x1080

#### Additional Information/Comments

tested both brave and edge

**Comment by shivaco** [comment] 2021-09-07 08:48
![image](https://user-images.githubusercontent.com/22858781/132314756-e7acf907-fdc0-4051-ab04-9531e5f0f4bb.png)
![image](https://user-images.githubusercontent.com/22858781/132314775-8ee861d5-d61a-4b07-ae94-27ee2f45bed9.png)

![image](https://user-images.githubusercontent.com/22858781/132314824-af585913-432b-44ca-93c2-0ca7ee3bc1f6.png)
![image](https://user-images.githubusercontent.com/22858781/132314830-b9d88d00-907c-4474-be23-4cd222cddc62.png)

**Comment by Raffa50** [comment] 2021-09-07 08:51
I'm not in top gg discord :P

**Comment by shivaco** [comment] 2021-09-07 08:54
[Feel free to join!](https://discord.gg/dbl) (:

To phrase my point into more serious words, the issue is known and Top.gg team is aware of it.

**Comment by Xetera** [comment] 2021-09-07 09:00
This should be fixed now

**Closed by Xetera** 2021-09-07 09:00 UTC
