### ISSUE TITLE
unable to login on top.ggi log in using my email and authorize the access to get to get my discord username and tag after that it doesn't log me in like it should)

### ISSUE THREAD

**Issue by acebolt** [top-gg/issues#594] opened 2021-02-20 06:25 UTC
#### Expected Behavior

I expected to find my bot MySuperBot

#### Observed Behavior

Instead I found this cat

#### Applicable Links or Attachments

![Image of the cat](https://top.gg/images/error.jpg)
[Link to MySuperBot](https://top.gg/bots/mysuperbot)

#### Steps to Reproduce

1. Open top.gg
2. ...

#### Web Browser and Version

Netscape navigator 9.0.0.6

#### Operating System and Version

Windows 98 SE

#### Screen Resolution

320×240

#### Additional Information/Comments

It might be because I visited a non existing page

**Comment by mrb23211** [comment] 2021-02-20 06:32
Use The Format

**Comment by Xignotic84** [comment] 2021-02-21 06:11
Duplicate of #593

**Closed by Xignotic84** 2021-02-21 06:11 UTC
Labels: Invalid
