### ISSUE TITLE
User react edit pages conflict with legacy redirects

### ISSUE THREAD

**Issue by verleuchtet** [top-gg/issues#717] opened 2021-05-27 08:15 UTC
#### Expected Behavior

Edit user information

#### Observed Behavior

Get 404/403/page does not load

https://user-images.githubusercontent.com/67605386/119790680-6a423480-bed4-11eb-8277-6302a95264e2.mp4

#### Steps to Reproduce

1. Open top.gg
2. Login to top.gg trough discord OAuth2
3. Click on the profilename
4. Click on edit profile
5. Click on invitations
6. Click on "User Info"
7. => You will get a 404 page
6. or click on subscriptions
7. => The page will not load
6. or click again on invitations
7. => You will get a 403 page 
How to fix?
Change the links, look at the redirect links of the anchors, the ID of the user has changed

#### Web Browser and Version

Firefox

#### Operating System and Version

Windows 10 Pro

#### Screen Resolution

2.560 x 1.440

**Comment by Xignotic84** [comment] 2021-05-27 08:33
Duplicate of #669

**Closed by Xignotic84** 2021-05-27 08:33 UTC
Labels: Bug
