### ISSUE TITLE
Remove Ads when voting for bots

### ISSUE THREAD

**Issue by Crewmategamingcoding** [top-gg/issues#477] opened 2020-11-06 18:57 UTC
#### Suggestion

We should remove ADs from voting because they are

- very annoying
- useless and damages user experiance
there's way WAY better ways to earn money like bitcoin mining or less annoying ads

**Comment by bobbaross** [comment] 2020-11-06 18:59
bitcoin mining?  ? ? ayo i'd be fine with ads over you mining on my pc

**Comment by Elara-Discord-Bots** [comment] 2020-11-06 18:59
Dupe of #457

**Comment by rlevet** [comment] 2020-11-06 19:00
bitcoin mining lmao

It's not considered as a malware for nothing, don't touch my CPU&Graphics card

**Closed** 2020-11-06 19:03 UTC
