### ISSUE TITLE
Looking for a way to get the reviews on top.gg to my webpage (could be a widget, API or else)

### ISSUE THREAD

**Issue by AlpDurak** [top-gg/issues#493] opened 2020-11-15 18:10 UTC
#### Suggestion
So I was trying to make a comment and review system on my bots web page and saw top.gg's new review system. So I thought it would be a good idea adding some API or Widget so we can get our reviews to show in our web pages.

Thanks for your services...

**Comment by Xignotic84** [comment] 2020-11-16 00:30
Duplicate of #492

**Closed by Xignotic84** 2020-11-16 00:30 UTC
