### ISSUE TITLE
I found a bug on the site

### ISSUE THREAD

**Issue by A7pekt** [top-gg/issues#415] opened 2020-08-24 11:06 UTC
![2020-08-24 (5)](https://user-images.githubusercontent.com/68823423/91038128-5141e580-e61b-11ea-8ed8-953156bf74c0.png)

some meg bot has no avatar

**Comment by marcorennmaus** [comment] 2020-08-24 11:10
Duplicate of #374

**Closed** 2020-08-24 11:10 UTC
