### ISSUE TITLE
403 when I try to visit my bot page.

### ISSUE THREAD

**Issue by real2two** [top-gg/issues#689] opened 2021-05-16 02:17 UTC
#### Expected Behavior

I should be able to go on my bot page.

#### Observed Behavior

On specifically beta mode (it works on the stable version), it gives me a 403 forbidden error when I try to view my bot's page.

#### Applicable Links or Attachments

![](https://media.discordapp.net/attachments/605561530565787648/843310334332895242/403_on_bot_page.png)

#### Steps to Reproduce

1. Open top.gg
2. Enable beta.
3. Try going on a bot page you own.

#### Web Browser and Version

Chrome "Version 90.0.4430.212 (Official Build) (64-bit)"

#### Operating System and Version

Windows 10 Home

#### Screen Resolution

I have no idea, and I really think this doesn't matter.

#### Additional Information/Comments

I don't know if this happens to other people though because it seems like I can't edit my bot page (for a while) on the stable version either giving me a 404.

**Comment by real2two** [comment] 2021-05-16 02:28
I somehow found a way to log out and keep the new beta design, and I can view my bot page when I'm logged out, but not when I'm logged in. .-.

**Comment by moyshik7** [comment] 2021-05-20 17:30
Is the bot verified ?

**Comment by Xignotic84** [comment] 2021-05-27 08:25
Can you please provide the URL of your bot page?

**Comment by real2two** [comment] 2021-05-27 16:26
https://top.gg/bot/716102473718169680

Still happening. Yes, the bot is verified. 

![](https://media.discordapp.net/attachments/605561530565787648/847510957512327188/Screenshot_4269.png)

**Comment by Xignotic84** [comment] 2021-05-28 02:34
Duplicate of #675

**Closed by Xignotic84** 2021-05-28 02:34 UTC
