### ISSUE TITLE
An option to view all reviews of bots, in different pages, or at least an option to view the latest 20 reviews when there are a lot of reviews for a bot

### ISSUE THREAD

**Issue by AwesomeStickz** [top-gg/issues#620] opened 2021-03-30 17:31 UTC
#### Suggestion

It would be great to have an option where you can see all the reviews of a bot, say in different pages instead of showing all reviews when there are more than 20 reviews in a bot. A lot of people who actually care about their users feedbacks would definitely love having this feature where they can see all reviews so that they could decide about how they could improve the bot further.

And you see, a lot of people who doesn't know how to use the bot and if they don't care to check those bot's help command or join its support server, they'll most likely leave a review saying "how to use the bot" and if we're able to see these reviews, we could tell them about how they can use the bot.

Or if this seems resource intensive, it'll be better to at least have an option with which you can see the latest 20 reviews made by people so that we could at least note the new people's thoughts on the bot/help them if they're just asking about a feature on the bot.

**Comment by Hopefuls** [comment] 2021-03-30 17:31
This will be something in the new design.

**Comment by Xignotic84** [comment] 2021-03-31 01:05
Duplicate of #553

**Closed by Xignotic84** 2021-03-31 01:05 UTC
