### ISSUE TITLE
DSL isn't working

### ISSUE THREAD

**Issue by CreightonJackson** [top-gg/issues#450] opened 2020-11-02 21:17 UTC
So when I go onto the website and add DSL to a server it doesn't show up on the website. Then I went to edit one of the servers I own and submit it, it removes it and when I search it up it won't give me the option to edit or delete, just report?

**Comment by Xignotic84** [comment] 2020-11-03 00:11
Duplicate of #447

**Comment by Xetera** [comment] 2020-11-07 02:25
This seems to be a separate problem as the linked issue was already resolved 3 days ago but I'm not unable to replicate this @CreightonJackson can you send your server ID and provide more detail?

**Comment by Xetera** [comment] 2020-11-12 15:07
Closing due to inactivity, feel free to reopen if your problem hasn't already been fixed

**Closed by Xetera** 2020-11-12 15:07 UTC
