### ISSUE TITLE
Moderation controls (Redesign)

### ISSUE THREAD

**Issue by asportnoy** [top-gg/issues#704] opened 2021-05-20 15:35 UTC
#### Expected Behavior

The "Moderation controls" are not shown since I am not a top.gg mod

#### Observed Behavior

They are shown in the redesign (not on the normal version)

#### Applicable Links or Attachments

![image](https://user-images.githubusercontent.com/14863373/119007442-d82bb080-b956-11eb-9341-2fe2542ceb98.png)

#### Steps to Reproduce

1. Log in as a non-mod account
2. Turn on the beta
3. Go to any bot page
4. Look in the bottom right

#### Web Browser and Version

Chrome 90.0.4430.212

#### Operating System and Version

macOS Big Sur

#### Screen Resolution

(2560 × 1600)

#### Additional Information/Comments

Only applies to redesign

**Comment by Xetera** [comment] 2021-05-20 16:07
Duplicate of #625

**Closed by Xetera** 2021-05-20 16:07 UTC
