### ISSUE TITLE
Webhook for Bot Reviews

### ISSUE THREAD

**Issue by Fyrlex** [top-gg/issues#498] opened 2020-11-20 04:00 UTC
#### Suggestion

Title kinda says it all, it could be posted to the same voting webhook URL and just call it Bot Webhook which will get votes and reviews.

Would be nice to allow devs to log the review messages, get author, and get rating.

**Comment by Xetera** [comment] 2020-11-20 07:52
Duplicate of #480

**Closed by Xetera** 2020-11-20 07:52 UTC
