### ISSUE TITLE
Increase session length to reduce the amount of times users need to login

### ISSUE THREAD

**Issue by 14ROVI** [top-gg/issues#487] opened 2020-11-11 07:55 UTC
I think top.gg should use the discord refresh tokens because that would mean users would have to log in less often. Logging in all the time is a pain if you are just visiting to vote but also generally.

**Comment by Xetera** [comment] 2020-11-11 08:30
Refresh tokens are only relevant for JWT based authentication which we don't use. The problem is with the max age of the cookie itself.

**Comment by Xignotic84** [comment] 2020-11-11 10:07
Duplicate of #329

**Closed by Xignotic84** 2020-11-11 10:07 UTC
Labels: DBL, DSL, Feature Request, Planned
