### ISSUE TITLE
Servers upvote screen

### ISSUE THREAD

**Issue by DeathFalconMik** [top-gg/issues#642] opened 2021-04-29 08:16 UTC
#### Expected Behavior

Uh no! You must be logged in to upvote servers!

#### Observed Behavior

Uh no! You must be logged in to upvote bots!

#### Applicable Links or Attachments

![Image of the responce](https://cdn.discordapp.com/attachments/714045415707770900/837235328863305749/unknown.png)
[Link to EAGLE CITY](https://top.gg/servers/749737924454645782/vote)

#### Steps to Reproduce

Can't as it is a spelling error and will occur when you want to upvote a server and you are not logged in.

#### Web Browser and Version

Google
Version 90.0.4430.93 (Official Build) (64-bit)

#### Operating System and Version

Edition	Windows 10 Home
Version	20H2
Installed on	‎2021/‎03/‎28
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0
![image](https://user-images.githubusercontent.com/67489117/116521201-f2ccb580-a8d3-11eb-9b18-996c0ea258dd.png)

#### Screen Resolution

1366*768 

#### Additional Information/Comments

I was going to upvote a server and not a bot.

**Comment by Hopefuls** [comment] 2021-04-29 09:06
Duplicate of https://github.com/top-gg/issues/issues/640

**Comment by Xignotic84** [comment] 2021-04-29 10:02
Duplicate of #640

**Closed by Xignotic84** 2021-04-29 10:02 UTC
