### ISSUE TITLE
Option to view more feedbacks

### ISSUE THREAD

**Issue by oriapp** [top-gg/issues#555] opened 2021-01-23 14:20 UTC
#### Suggestion

As for now, In TOP.GG bot who have more then 20 feedbacks can not see newer feedbacks about the bot and ratings.
and this is a problem for both sides (users who what's to see what people say about this bot and bot developers) and once you have more than 20 feedbacks you just can't see and understand what people want to improve and etc. 

I would be nice if you could add some paginate or in the edit page something for the bot devs, at the end we want to improve and get all the feedback if it's good and if it's not.

**Comment by Xignotic84** [comment] 2021-01-23 15:16
Duplicate of #553

**Closed by Xignotic84** 2021-01-23 15:16 UTC
