### ISSUE TITLE
Bug Report with adding bots

### ISSUE THREAD

**Issue by Day-Codes** [top-gg/issues#794] opened 2021-09-01 19:21 UTC
#### Expected Behavior
For me to get into the site to add a bot

#### Observed Behavior

I found that it brings you to top.gg login discord and wont bring you back and just keep loading and wont stop

#### Applicable Links or Attachments
https://cdn.discordapp.com/attachments/882351831093743646/882706654888624178/Screenshot_2021-09-01_3.20.16_PM.png

![Image of the cat](https://top.gg/images/error.jpg)
[Link to MySuperBot](https://top.gg/bots/mysuperbot)

#### Steps to Reproduce

1. Open top.gg
2. ...

#### Web Browser and Version

Netscape navigator 9.0.0.6

#### Operating System and Version

Windows 98 SE

#### Screen Resolution

320×240

#### Additional Information/Comments

It might be because I visited a non existing page

**Comment by ExtremeDevelopments** [comment] 2021-09-01 21:11
Duplicate of #791, read the comments for more information on this bug.

**Comment by marcorennmaus** [comment] 2021-09-04 19:48
Duplicate of #791 
Also most of the details of the template weren't actually filled out

**Closed by marcorennmaus** 2021-09-04 19:48 UTC
