### ISSUE TITLE
queue automation with uptime

### ISSUE THREAD

**Issue by GalaxySH** [top-gg/issues#440] opened 2020-10-11 00:50 UTC
#### Suggestion

1) your bot that you are submitting must be in **some server, not the DBL server** (like a support server), with a bot that DBL owns
2) when the bot is submitted for approval, the DBL bot is added to the server with the bot
3) because they are now in a mutual permanent server, the DBL bot will check the bot's status
4) the DBL bot will log the offline time, **if it exceeds a certain *percent*, it will be removed from queue**
5) if the server it was on mutually with is deleted, or the bot kicked, it is also removed from queue
6) since most bots are declined for being offline, this would hopefully eliminate a lot of those bots **ahead of time**

**This proposes something that can be done with some development to help automate the DBL's approval process**. This would involve making a DBL bot that people would **add to their support servers** (they would have to have a support server that their bot is in the whole time they are in the queue). This bot would check and log all statuses of bots in the queue, like, hourly (or daily, because that is a lot of bots). It would check to see what the downtime (in %) is for the bot, and after a week in the queue (because if it is offline the first day it would %100 downtime), and if it exceeds a certain % of downtime, it would get auto-removed **and the queue would get shorter**. I heard from the moderators that the number 1 reason for declination was the bot being offline when selected for review, and this would help. If the bot downtime % exceeds %50, then statistically it would probably be offline during review, which is a reason for rejection. You might not like that it might happen to be online when they actually check it, but I think the queue is way too long for that to be a reason not to implement this. With this proposal, if you want your bot approved, work on making it have a really good uptime. Plus, having a good uptime counts toward the bot being higher quality, which is something that DBL says they want on their list.

I don't think the mods and policies can afford to just say stuff like "we don't care how long it takes" and "we don't care if the bot is offline the entire time it was in the queue except when we reviewed it" anymore. They especially shouldn't say this now that with every week spent in the queue, another week is added to the ETR. They may just be volunteers that don't give a crap about the queue, but a lot of the people in the queue don't appreciate that. Bot developers don't like waiting in the queue for...years, it seems like, and the moderators don't like having those submitters come and bother them on the DBL server about it. The mods also don't like having to ban all those people, I would assume. And while the mods are away either babysitting/dealing with the rest of the people in the server or just not giving a s***, those bots are just sitting there. And while in the queue, those people that submitted them are just giving up or getting mad at DBL because their bots (and some might actually be really good) are just sitting there in their support servers, not getting added or used, making Discord, development, and DBL a phat waste of time.

More needs to be done to shorten the queue! I have seen a lot of people on DBL say stuff like, "just be patient," but that is just dumb. They may not ever care if their bot is in the list, most of the people who add a bot will forget, or possibly even stop developing their bot, but people like me would actually like to get their bot approved.

There are other ways the process can be improved, and even automated, but this was just one I thought of quickly. The queue is really long, and DBL should definitely consider doing something besides just depend on a few volunteers to come online once in a while to reject a few and leave the queue alone again for days. It looks like DBL has a lot of moderators, and barely any of them bother with the queue, judging by the mod-logs.

**Comment by Xignotic84** [comment] 2020-10-12 23:58
Duplicate of #416

**Closed by Xignotic84** 2020-10-12 23:58 UTC
