### ISSUE TITLE
Add twemoji support

### ISSUE THREAD

**Issue by Luke-6723** [top-gg/issues#797] opened 2021-09-06 03:37 UTC
#### Suggestion

Adding twemoji support to top.gg long/short description.

Would allow easy use of emojis and adds site wide support for emojis on machines that may be missing font entirely.

#### Applicable Links or Attachments

![Example image](https://user-images.githubusercontent.com/80823011/132134444-7a776832-3001-4071-8e18-c6b606f96275.jpg)

**Comment by ExtremeDevelopments** [comment] 2021-09-06 03:42
Twemoji script link: https://twemoji.maxcdn.com/v/latest/twemoji.min.js

**Comment by velddev** [comment] 2021-09-06 17:52
Duplicate of #626

**Closed by velddev** 2021-09-06 17:52 UTC
