### ISSUE TITLE
Replying to a review causes the user to submit their own review

### ISSUE THREAD

**Issue by goverfl0w** [top-gg/issues#685] opened 2021-05-15 13:27 UTC
#### Expected Behavior

When replying to a review left on your bot page(s) listed as owner or co-owner, it should show in-line as the bot.

#### Observed Behavior

Instead, this shows as the user themselves making the reply.

#### Applicable Links or Attachments

![oh my god this is torture i need sleep help i've made 20 of these issues so far](https://i.imgur.com/NB2B36f.png)

#### Steps to Reproduce

1. Open top.gg
2. Go to a bot page you own or are co-owner of
3. Make a reply to a review not yet replied to
4. Observe and wait for the effect to take in. (This may take some time as there seems to be a long buffer)

#### Additional Information/Comments

Could be related to #671 .

**Comment by marcorennmaus** [comment] 2021-05-15 14:45
Correction: Replying to a review causes you to submit your own review with 0 stars

**Comment by goverfl0w** [comment] 2021-05-15 14:46
Yeah I noticed that too but wasn't sure if that was totally intentional since it makes the instance of you being the reply of the review.

**Comment by pixxies** [comment] 2021-05-16 00:18
Duplicate of #671

**Closed** 2021-05-16 01:53 UTC
