### ISSUE TITLE
Integrate bot reviews into DBL's API

### ISSUE THREAD

**Issue by SinistreCyborg** [top-gg/issues#492] opened 2020-11-15 12:39 UTC
- The bot object should include an array of all the reviews the bot has and the rating that each reviewer gave, and an integer for the average rating the bot has.
 - We should be able to set up a separate webhook to be alerted when our bot gets a new review

**Comment by Xetera** [comment] 2020-11-20 07:52
Duplicate of #480

**Closed by Xetera** 2020-11-20 07:52 UTC
Labels: DBL, Feature Request
