### ISSUE TITLE
Suggestion: add a /bots/${bot.id}/comments endpoint

### ISSUE THREAD

**Issue by AlexIsOK** [top-gg/issues#563] opened 2021-01-29 19:27 UTC
There should be a /bots/botid/comments endpoint that allows you to get the comments of a bot.  May be useful for bot developers to check if anyone has commented on their bot and notify them.

**Comment by Xignotic84** [comment] 2021-01-31 08:14
Duplicate of #480

**Closed by Xignotic84** 2021-01-31 08:14 UTC
