### ISSUE TITLE
Verification related 

### ISSUE THREAD

**Issue by HyperCoder11** [top-gg/issues#610] opened 2021-03-21 16:56 UTC
You should keep high priorities for verified bots by discord. I do understand u have 1000's of bot requests coming in a day. Maybe you should have a separation between verified by discord and non verified. So it can be easier for developers. So maybe if you could convey this message to people higher it would be a great help. Cause i was waiting for over 2 weeks for the first application and then another 2 weeks for my 2nd request. So u can say am waiting from feb 1st week.So it would be a great help if you guys have seperations. Some people (verified guys) wait for a long time to get approved.

Regards
DarkHyperGamer#8115

**Comment by Faith1sGay** [comment] 2021-03-21 17:06
Okay? Congrats on your bot being verified by discord but that doesn't give you priority, and it shouldn't. Top.gg reviews all bots fairly and similarly.

**Comment by shivaco** [comment] 2021-03-21 17:10
While I see why this happens to be your opinion regarding this, I strongly disagree with it and I am inclined to believe the queue system will not change to treat verified bots any differently than non-verified ones. Main reason for that is ***very possibly*** due to the fact that verification is mandatory for public bots, and does not grant any specific perks to bots per se.

**Comment by HyperCoder11** [comment] 2021-03-21 17:17
Na mate you got me wrong. I never said spacial perks. I just said in favour of all the Developers around the world. And am ain't saying that small bots don't have potential. They would have bigger potential than the top bots in the discord platform. So don't get me wrong there. I gave a suggestion for a bit speed checking cause verified bots don't have major and daily breakdowns. If that was the case discord themself would decline the bot. I just told Instead of detailed check and precise checking. You could speed check everything. And that would save time then waiting for 2 months.

**Comment by takipsizad** [comment] 2021-03-21 17:25
bruh it is bad idea

**Comment by shivaco** [comment] 2021-03-21 17:31
That depends.

Queue does not exactly consist of verified bots, so best you would get is a few days **max** decrease in wait time.

Having reviewed bots myself, my personal stance on this has not changed in months by now. Top.gg claims and intends to be a website for all aspiring developers to have their creations recognized, and giving verified bots special treatment will only go against that policy.

Applying my experience, I have reviewed and observed verified bots go through just as much hassle as non-verified bots do. What I mean, is that some verified bots I have reviewed have been utter garbage, just like non-verified bots were more decent. Reviewing verified bots simply says that a bot has a userbase that actively uses it.

Side note, Discord rely on bot list websites in the first place to verify bots in the first place.

**Comment by jpbberry** [comment] 2021-03-21 17:31
I kind of agree with this, though I heavily doubt this'll ever happen. There's something to be said since for smaller bots, the speed at which you get on Top.gg is very insignificant and just an annoyance. But there's a point to be said, for if you blow up and you want to be added to Top.gg, speed can be difference between hundreds of servers and views, which isn't the case for unverified/smaller bots, because they're not even kickstarted until they're on the platform in the first place.

**Comment by NMW03** [comment] 2021-03-21 17:32
Verification is ~mandatory for every public bot. That's why prioritizing verified bots is unnecessary and illogical

**Comment by takipsizad** [comment] 2021-03-21 17:32
idea is good but i dont think this is done

**Comment by ExtremeDevelopments** [comment] 2021-03-21 17:33
I strongly disagree with the idea of this as the queue is meant to be fair across all users and developers. Also, verification is mandatory for every public bot which makes us prioritizing a verified bot over others is not very realistic in my eyes.

**Comment by jpbberry** [comment] 2021-03-21 17:34
> Verification is ~mandatory for every public bot. That's why prioritizing verified bots is unnecessary and illogical

I think it's more about how large a bot is rather than the fact that they're verified. Verification would just be an easy way to gage and create a baseline for speedier queue times based on server count.

**Comment by takipsizad** [comment] 2021-03-21 17:34
laughs having public bot without verified

**Comment by shivaco** [comment] 2021-03-21 17:35
> > Verification is ~mandatory for every public bot. That's why prioritizing verified bots is unnecessary and illogical
> 
> I think it's more about how large a bot is rather than the fact that they're verified. Verification would just be an easy way to gage and create a baseline for speedier queue times based on server count.

That would mean that larger bots are prioritized, which, still, goes against Top.gg's inclusiveness in terms of queue policies.

**Comment by HyperCoder11** [comment] 2021-03-21 17:36
> I kind of agree with this, though I heavily doubt this'll ever happen. There's something to be said since for smaller bots, the speed at which you get on Top.gg is very insignificant and just an annoyance. But there's a point to be said, for if you blow up and you want to be added to Top.gg, speed can be difference between hundreds of servers and views, which isn't the case for unverified/smaller bots, because they're not even kickstarted until they're on the platform in the first place.

And I said this cause many scam bots like nitro generator bots (example) they come to top.gg and keep a queue and the people (verified) have to wait a god damn month or two. Just to get allowance to use the site (no offense). But I strongly feel the verified ones and the non verified (no offense) should be seperated and finished at a higher pace. If everyone's gonna wait a month or two it's pissing off.

**Comment by jpbberry** [comment] 2021-03-21 17:36
Good point

**Comment by ExtremeDevelopments** [comment] 2021-03-21 17:36
After doing queue for about 4 months now, I have seen barely any verified bots get tested by me or seen anyone mention it... I would say I have probably tested at maximum 10 bots that were verified at the testing stage. With the statistics that could be provided from the staff team, it just seems illogical to do this with the amount of verified bots compared to unverified bots that are added to the queue.

**Comment by takipsizad** [comment] 2021-03-21 17:37
yup

**Comment by jpbberry** [comment] 2021-03-21 17:37
> That would mean that larger bots are prioritized, which, still, goes against Top.gg's inclusiveness in terms of queue policies.

Yeah of course, the point of the issue is to maybe switch up said policy

**Comment by shivaco** [comment] 2021-03-21 17:38
> > That would mean that larger bots are prioritized, which, still, goes against Top.gg's inclusiveness in terms of queue policies.
> 
> Yeah of course, the point of the issue is to maybe switch up said policy

I highly doubt it is feasible in a manner that would not cause backlash, putting generally unfair treatment aside.

**Comment by jpbberry** [comment] 2021-03-21 17:39
> ... I have seen barely any verified bots get tested by me or seen anyone mention it... I would say I have probably tested at maximum 10 bots that were verified at the testing stage. ...

Wouldn't this be a reason towards it? If there's only like 10 verified bots you review, fast tracking them would make nearly no difference to unverified bots

**Comment by HyperCoder11** [comment] 2021-03-21 17:40
> After doing queue for about 4 months now, I have seen barely any verified bots get tested by me or seen anyone mention it... I would say I have probably tested at maximum 10 bots that were verified at the testing stage. With the statistics that could be provided from the staff team, it just seems illogical to do this with the amount of verified bots compared to unverified bots that are added to the queue.

I just made a suggestion and it's not gonna be a fight so peace out. I told this cause am waiting over 2 months. And still hasn't been approved. I had to even fill the bot application thrice

**Comment by HyperCoder11** [comment] 2021-03-21 17:42
> > ... I have seen barely any verified bots get tested by me or seen anyone mention it... I would say I have probably tested at maximum 10 bots that were verified at the testing stage. ...
> 
> Wouldn't this be a reason towards it? If there's only like 10 verified bots you review, fast tracking them would make nearly no difference to unverified bots

This is what an god damn yelling about

**Comment by jpbberry** [comment] 2021-03-21 17:44
Please keep the discussion civil, there's no fighting going on, just legitimate discussion that could possibly spark change.

As for your bot, it was denied on the platform, I'd resubmit it and make sure it works. Ask in support for the reason of abnormally long queue times (1+ month)

**Comment by HyperCoder11** [comment] 2021-03-21 17:46
> Please keep the discussion civil, there's no fighting going on, just legitimate discussion that could possibly spark change.
> 
> As for your bot, it was denied on the platform, I'd resubmit it and make sure it works. Ask in support for the reason of abnormally long queue times (1+ month)
For your info I submitted the bot cause it was declined twice. Both for the bot going offline. The reason was cause we do daily bug fixes and updates. And it isn't daily breskdown

**Comment by Prathmesh-Chalia** [comment] 2021-03-21 17:48
i agree

**Comment by MartinItsLinda** [comment] 2021-03-21 17:49
> > Please keep the discussion civil, there's no fighting going on, just legitimate discussion that could possibly spark change.
> > As for your bot, it was denied on the platform, I'd resubmit it and make sure it works. Ask in support for the reason of abnormally long queue times (1+ month)
> 
> For your info I submitted the bot cause it was declined twice. Both for the bot going offline. The reason was cause we do daily bug fixes and updates. And it isn't daily breakdowns

That's not TopGG's issue, you shouldn't be doing daily bug fixes and instead be following a specific maintenance period which you can mention on your page and TopGG to my knowledge will allow for this. You can't blame TopGG for an issue which you caused.

**Comment by dawnofmidnight** [comment] 2021-03-21 17:50
I suggest you fix your bot on an Alpha version, and then you can push changes quickly.

**Comment by jpbberry** [comment] 2021-03-21 17:50
Please keep discussion about the status of your bot in the queue / ways to work with it out of this specific thread. I'd recommend moving to #general.

**Comment by shivaco** [comment] 2021-03-21 17:51
> > ... I have seen barely any verified bots get tested by me or seen anyone mention it... I would say I have probably tested at maximum 10 bots that were verified at the testing stage. ...
> 
> Wouldn't this be a reason towards it? If there's only like 10 verified bots you review, fast tracking them would make nearly no difference to unverified bots

Do you believe this will be a solution for the current wait times in the long term? I doubt it will help much to justify the possibility of a policy change, especially considering how people may start merely considering themselves unequal from verified bots. That could cause quite a havoc, if you see what I mean.

**Comment by HyperCoder11** [comment] 2021-03-21 17:51
> > Please keep the discussion civil, there's no fighting going on, just legitimate discussion that could possibly spark change.
> > 
> > As for your bot, it was denied on the platform, I'd resubmit it and make sure it works. Ask in support for the reason of abnormally long queue times (1+ month)
> For your info I submitted the bot cause it was declined twice. Both for the bot going offline. The reason was cause we do daily bug fixes and updates. And it isn't daily breskdown
> 

Bruh why do u take it wrong. All new bots need bug fixes. We aren't Dyno or mee6 here. If Ur bot isn't responding to certain command. Will you wait for a miracle to fix it?( not fighting just for Ur realization) and I never blamed on top

**Comment by shivaco** [comment] 2021-03-21 17:52
> > > Please keep the discussion civil, there's no fighting going on, just legitimate discussion that could possibly spark change.
> > > As for your bot, it was denied on the platform, I'd resubmit it and make sure it works. Ask in support for the reason of abnormally long queue times (1+ month)
> > > For your info I submitted the bot cause it was declined twice. Both for the bot going offline. The reason was cause we do daily bug fixes and updates. And it isn't daily breskdown
> 
> Bruh why do u take it wrong. All new bots need bug fixes. We aren't Dyno or mee6 here. If Ur bot isn't responding to certain command. Will you wait for a miracle to fix it?( not fighting just for Ur realization) and I never blamed on top

We suggest you keep this discussion for the Discord or just end it there. Let's keep it professional, shall we? 😁

**Comment by HyperCoder11** [comment] 2021-03-21 17:53
> > > ... I have seen barely any verified bots get tested by me or seen anyone mention it... I would say I have probably tested at maximum 10 bots that were verified at the testing stage. ...
> > 
> > Wouldn't this be a reason towards it? If there's only like 10 verified bots you review, fast tracking them would make nearly no difference to unverified bots
> 
> Do you believe this will be a solution for the current wait times in the long term? I doubt it will help much to justify the possibility of a policy change, especially considering how people may start merely considering themselves unequal from verified bots. That could cause quite a havoc, if you see what I mean.

Take urself in the matter. And think about it. You will know

**Comment by Prathmesh-Chalia** [comment] 2021-03-21 17:53
ok so let me introduce myself
I am the lead developer of tones
My friend, suzcat handles the bug fixes and ik its really not manageable to accept a bot that i usually offline but we will try our best to not let that happen again .I am sorry for any inconveniences.

**Comment by jpbberry** [comment] 2021-03-21 17:53
> > > ... I have seen barely any verified bots get tested by me or seen anyone mention it... I would say I have probably tested at maximum 10 bots that were verified at the testing stage. ...
> > 
> > 
> > Wouldn't this be a reason towards it? If there's only like 10 verified bots you review, fast tracking them would make nearly no difference to unverified bots
> 
> Do you believe this will be a solution for the current wait times in the long term? I doubt it will help much to justify the possibility of a policy change, especially considering how people may start merely considering themselves unequal from verified bots. That could cause quite a havoc, if you see what I mean.

I mean realistically, the change isn't to change the queue times, rather give bigger bots an incentive and also a quicker turnaround time during what is undoubtedly an important time period when a bigger bot needs to be added to the platform. If it takes two weeks to get onto the platform after your bot has blown up, that turnaround time is super important, because by the end of the 2 weeks it might be irrelevant already.

**Comment by HyperCoder11** [comment] 2021-03-21 17:55
> > > > ... I have seen barely any verified bots get tested by me or seen anyone mention it... I would say I have probably tested at maximum 10 bots that were verified at the testing stage. ...
> > > 
> > > 
> > > Wouldn't this be a reason towards it? If there's only like 10 verified bots you review, fast tracking them would make nearly no difference to unverified bots
> > 
> > Do you believe this will be a solution for the current wait times in the long term? I doubt it will help much to justify the possibility of a policy change, especially considering how people may start merely considering themselves unequal from verified bots. That could cause quite a havoc, if you see what I mean.
> 
> I mean realistically, the change isn't to change the queue times, rather give bigger bots an incentive and also a quicker turnaround time during what is undoubtedly an important time period when a bigger bot needs to be added to the platform. If it takes two weeks to get onto the platform after your bot has blown up, that turnaround time is super important, because by the end of the 2 weeks it might be irrelevant already.

Yes mate totally with it

**Comment by shivaco** [comment] 2021-03-21 17:57
> > > > ... I have seen barely any verified bots get tested by me or seen anyone mention it... I would say I have probably tested at maximum 10 bots that were verified at the testing stage. ...
> > > 
> > > 
> > > Wouldn't this be a reason towards it? If there's only like 10 verified bots you review, fast tracking them would make nearly no difference to unverified bots
> > 
> > 
> > Do you believe this will be a solution for the current wait times in the long term? I doubt it will help much to justify the possibility of a policy change, especially considering how people may start merely considering themselves unequal from verified bots. That could cause quite a havoc, if you see what I mean.
> 
> Take urself in the matter. And think about it. You will know

On quite multiple occasions, I actually have. However, my point of view remains the same. Top.gg prefer to stay neutral and treat bot reviewing equal.

If I submit a bot, I get placed in the queue and since it is meant to be fair for everyone, I just keep my patience. Just because my bot has managed to get more traction than others does not invalidate the efforts of other developers who are in the same queue as me.

**Comment by MartinItsLinda** [comment] 2021-03-21 17:58
> > > Please keep the discussion civil, there's no fighting going on, just legitimate discussion that could possibly spark change.
> > > As for your bot, it was denied on the platform, I'd resubmit it and make sure it works. Ask in support for the reason of abnormally long queue times (1+ month)
> > > For your info I submitted the bot cause it was declined twice. Both for the bot going offline. The reason was cause we do daily bug fixes and updates. And it isn't daily breskdown
> 
> Bruh why do u take it wrong. All new bots need bug fixes. We aren't Dyno or mee6 here. If Ur bot isn't responding to certain command. Will you wait for a miracle to fix it?( not fighting just for Ur realization) and I never blamed on top

Correct me if I'm wrong but nobody ever said bots don't need bug fixes? Sure, issues happen, and when they do we as developers have a responsibility to fix them. But it is also your responsibility to set times where your bot should be under a maintenance period and it is also your responsibility to inform any users of your bot to inform people of those periods.

**Comment by dawnofmidnight** [comment] 2021-03-21 18:00
> I mean realistically, the change isn't to change the queue times, rather give bigger bots an incentive and also a quicker turnaround time during what is undoubtedly an important time period when a bigger bot needs to be added to the platform. If it takes two weeks to get onto the platform after your bot has blown up, that turnaround time is super important, because by the end of the 2 weeks it might be irrelevant already.

I totally agree.

The one issue is that top.gg is how many bots get big in the first place. Some people don't have any other way to do so, and top.gg is the only way for them to advertise. (That is, unless they use other listing sites, which hurts the business model.) Giving verified bots is providing an unfair advantage, which is against the top.gg goal which is to be *impartial*.

**Comment by HyperCoder11** [comment] 2021-03-21 18:00
> > > > Please keep the discussion civil, there's no fighting going on, just legitimate discussion that could possibly spark change.
> > > > As for your bot, it was denied on the platform, I'd resubmit it and make sure it works. Ask in support for the reason of abnormally long queue times (1+ month)
> > > > For your info I submitted the bot cause it was declined twice. Both for the bot going offline. The reason was cause we do daily bug fixes and updates. And it isn't daily breskdown
> > 
> > Bruh why do u take it wrong. All new bots need bug fixes. We aren't Dyno or mee6 here. If Ur bot isn't responding to certain command. Will you wait for a miracle to fix it?( not fighting just for Ur realization) and I never blamed on top
> 
> Correct me if I'm wrong but nobody ever said bots don't need bug fixes? Sure, issues happen, and when they do we as developers have a responsibility to fix them. But it is also your responsibility to set times where your bot should be under a maintenance period and it is also your responsibility to inform any users of your bot to inform people of those periods.

Is that possible with the bot reviewer no way!!

**Comment by HyperCoder11** [comment] 2021-03-21 18:01
> > I mean realistically, the change isn't to change the queue times, rather give bigger bots an incentive and also a quicker turnaround time during what is undoubtedly an important time period when a bigger bot needs to be added to the platform. If it takes two weeks to get onto the platform after your bot has blown up, that turnaround time is super important, because by the end of the 2 weeks it might be irrelevant already.
> 
> I totally agree.
> 
> The one issue is that top.gg is how many bots get big in the first place. Some people don't have any other way to do so, and top.gg is the only way for them to advertise. (That is, unless they use other listing sites, which hurts the business model.) Giving verified bots is providing an unfair advantage, which is against the top.gg goal which is to be impartial. 

This is exactly my point 💯

**Comment by jpbberry** [comment] 2021-03-21 18:01
Again please keep the discussion civil and on-topic. The derailment of this thread has probably already scratched the original idea at this point.

**Comment by HyperCoder11** [comment] 2021-03-21 18:01
Anyways am closing this thanks Guys

**Comment by MartinItsLinda** [comment] 2021-03-21 18:02
> > > > > Please keep the discussion civil, there's no fighting going on, just legitimate discussion that could possibly spark change.
> > > > > As for your bot, it was denied on the platform, I'd resubmit it and make sure it works. Ask in support for the reason of abnormally long queue times (1+ month)
> > > > > For your info I submitted the bot cause it was declined twice. Both for the bot going offline. The reason was cause we do daily bug fixes and updates. And it isn't daily breskdown
> > > 
> > > 
> > > Bruh why do u take it wrong. All new bots need bug fixes. We aren't Dyno or mee6 here. If Ur bot isn't responding to certain command. Will you wait for a miracle to fix it?( not fighting just for Ur realization) and I never blamed on top
> > 
> > 
> > Correct me if I'm wrong but nobody ever said bots don't need bug fixes? Sure, issues happen, and when they do we as developers have a responsibility to fix them. But it is also your responsibility to set times where your bot should be under a maintenance period and it is also your responsibility to inform any users of your bot to inform people of those periods.
> 
> Is that possible with the bot reviewer no way!!

Being rude is absolutely no way to get what you want in any community, if you want something to happen you should go about it in a constructive and civil manner.

**Comment by dawnofmidnight** [comment] 2021-03-21 18:02
> This is exactly my point 💯

If this is your point, then why are you proposing this? I just gave a reason to not do this.

**Comment by shivaco** [comment] 2021-03-21 18:03
> > > > ... I have seen barely any verified bots get tested by me or seen anyone mention it... I would say I have probably tested at maximum 10 bots that were verified at the testing stage. ...
> > > 
> > > 
> > > Wouldn't this be a reason towards it? If there's only like 10 verified bots you review, fast tracking them would make nearly no difference to unverified bots
> > 
> > 
> > Do you believe this will be a solution for the current wait times in the long term? I doubt it will help much to justify the possibility of a policy change, especially considering how people may start merely considering themselves unequal from verified bots. That could cause quite a havoc, if you see what I mean.
> 
> I mean realistically, the change isn't to change the queue times, rather give bigger bots an incentive and also a quicker turnaround time during what is undoubtedly an important time period when a bigger bot needs to be added to the platform. If it takes two weeks to get onto the platform after your bot has blown up, that turnaround time is super important, because by the end of the 2 weeks it might be irrelevant already.

What specifically dictates the mentioned "need"? Why does it relate to a bot with a larger userbase?

I doubt that that is the original idea, since the post has not mentioned making it easier for *verified* developers, but rather just developers generally.

**Comment by HyperCoder11** [comment] 2021-03-21 18:03
> > > > > > Please keep the discussion civil, there's no fighting going on, just legitimate discussion that could possibly spark change.
> > > > > > As for your bot, it was denied on the platform, I'd resubmit it and make sure it works. Ask in support for the reason of abnormally long queue times (1+ month)
> > > > > > For your info I submitted the bot cause it was declined twice. Both for the bot going offline. The reason was cause we do daily bug fixes and updates. And it isn't daily breskdown
> > > > 
> > > > 
> > > > Bruh why do u take it wrong. All new bots need bug fixes. We aren't Dyno or mee6 here. If Ur bot isn't responding to certain command. Will you wait for a miracle to fix it?( not fighting just for Ur realization) and I never blamed on top
> > > 
> > > 
> > > Correct me if I'm wrong but nobody ever said bots don't need bug fixes? Sure, issues happen, and when they do we as developers have a responsibility to fix them. But it is also your responsibility to set times where your bot should be under a maintenance period and it is also your responsibility to inform any users of your bot to inform people of those periods.
> > 
> > Is that possible with the bot reviewer no way!!
> 
> Being rude is absolutely no way to get what you want in any community, if you want something to happen you should go about it in a constructive and civil manner. 

Ur taking it wrong 🤷

**Comment by HyperCoder11** [comment] 2021-03-21 18:03
> > This is exactly my point 💯
> 
> If this is your point, then why are you proposing this? I just gave a reason to not do this. 😕

Ur first sentence is what I felt. So am closing it

**Closed** 2021-03-21 18:04 UTC

**Comment by Prathmesh-Chalia** [comment] 2021-03-21 18:14
a
### 

> 

> 

> [****](

- 

- [ ] url

)

**Comment by TAG-Epic** [comment] 2021-03-21 20:46
If I understood this correctly:
You want verified bots to have a sort of "priority queue?" because they are easier to review and shouldn't violate the rules.

Alright so I disagree on this. I have a bot which used to be in 400 servers, which used to violate the rules and was buggy and honestly low quality.

 I believe that every single bot in the top.gg queue should get the same treatment. Verification is not a sign/badge of being a ToS compliant bot nor a stable bot. It's only a way to know discord can hunt you down if you did something bad.

**Comment by Xetera** [comment] 2021-03-21 20:54
I can't comment on whether or not this will be added because this isn't something we've discussed before but it seems unlikely considering how few already-verified bots apply and the fact that the application process is a one time thing for an overwhelming number of developers, who represent a very small percentage of the userbase.
It just doesn't make much sense to take time away from development to implement this even if it was a good idea (which it probably isn't anyways).
