### ISSUE TITLE
Add a automatic system in Luca that will check if the bot added into the test server is offline or not.

### ISSUE THREAD

**Issue by ExtremeDevelopments** [top-gg/issues#438] opened 2020-10-10 19:23 UTC
### Suggestion

Allow Luca to automatically check the bots status upon joining and send an embedded message with information about the bot from the queue. Then add a reaction to the bottom of the message which a mod can click and it will automatically decline the bot under the mods name with a preset message.
This can greatly increase the speed of the queue because it will be faster to deny offline bots from the queue which is a large amount of the queue.

#### Applicable Links or Attachments
![image](https://user-images.githubusercontent.com/48730677/95663046-6dcdaa80-0b01-11eb-82f9-9bc53fd6e3b7.png)
This is an example of the number of bots that were denied for being offline today.
![image](https://user-images.githubusercontent.com/48730677/95663056-8938b580-0b01-11eb-996b-015a29909455.png)
This is the amount this week.

Code Example: 
![image](https://user-images.githubusercontent.com/48730677/95663355-314f7e00-0b04-11eb-9b09-23e26cde2174.png)
If source needed, dm me at Extreme#1000 on discord.
Comments appreciated!

**Comment by shivaco** [comment] 2020-10-10 19:28
One main reason why this has not been already implemented is that we give bots a small window of time to come online to review them. If they are still offline by then, we decline them.

As for the other part with reactions, it's pointless compared to the system we have in place.

**Comment by erwin1234777** [comment] 2020-10-10 23:02
![Code_dPdz2rry1K](https://user-images.githubusercontent.com/29512349/95666759-47286780-0b33-11eb-8603-c1a7c5abaf60.png)
@ExtremeDevelopments asked me to post this here.
just an idea, assign a score based system that is checked hourly per bot. If they dont have the minimum score every 24h, or per week, auto decline them. 
Simple yet efficient(without accounting for new joins, either automate it daily so you have a clean pallete to work with or account for new bots).
Add all bots to a list.
every hour, check each bot, if its online => give it 1+ point
by the end of the final check(in my case 24h, change it to weekly) if it doesnt have x amount of points (say, 80% uptime), autodecline

**Comment by Xignotic84** [comment] 2020-10-12 23:58
Duplicate of #416

**Closed by Xignotic84** 2020-10-12 23:58 UTC
