### ISSUE TITLE
Unable to log in to top.gg.

### ISSUE THREAD

**Issue by platonicvibes** [top-gg/issues#588] opened 2021-02-19 02:32 UTC
#### Expected Behavior

When clicking a link in a Discord server to vote on a bot on top.gg, I was redirected to log in; I expected to be able to authorize and log in.

#### Observed Behavior

Instead when clicking the 'authorize' button when redirected to Discord, I was brought back to top.gg and told I needed to log in. I tried to log in on the main page as well, to no success. When experimenting by opening the 'Subscribe to Premium' link, I got stuck in an endless loop on Discord: click the button, the page refreshes and I hit 'authorize' again, ad infinitum. No login.

#### Applicable Links or Attachments

Image of authorization screen on Discord: (https://i.imgur.com/6NYcPXC.png)
Image of top.gg after clicking 'authorize': (https://i.imgur.com/NyOz52m.png)

#### Steps to Reproduce

1. Open top.gg
2. Click 'Login.'
3. Click 'Authorize' when asked if Discord Bot List can access your account.
4. Be brought back to top.gg, not logged in.

#### Web Browser and Version

Microsoft Edge Version 88.0.705.68; also tested in the latest version of Google Chrome.

#### Operating System and Version

Windows 10

#### Screen Resolution

1920x1080

#### Additional Information/Comments

My Discord account is brand new, though I'm uncertain if this has any relation.

**Comment by WireSplitter** [comment] 2021-02-19 20:34
I have the same problem, but my Discord account is not brand new. I have not logged into top.gg before, though. I think it may be a recent issue with logging in for the first time.

**Comment by marcorennmaus** [comment] 2021-02-19 20:44
Duplicate of #586

**Closed by marcorennmaus** 2021-02-19 20:44 UTC
