### ISSUE TITLE
Moderation tools present without moderator status.

### ISSUE THREAD

**Issue by goverfl0w** [top-gg/issues#659] opened 2021-05-14 01:28 UTC
#### Expected Behavior

You are not able to see the moderator popup in the bottom right without being a moderator.

#### Observed Behavior

I see them.

#### Applicable Links or Attachments

![Image showing the bug.](https://i.imgur.com/2OPJhwn.png)

#### Steps to Reproduce

1. Open top.gg
2. Login
3. Go-to your bot page.
4. Observe.

#### Web Browser and Version

Google Chrome 90.0.4430.212 (Official Build) (64-bit)

#### Operating System and Version

Windows 10 Version 10.0.19042 Build 19042

#### Screen Resolution

1920×1080

#### Additional Information/Comments

N/A.

**Comment by marcorennmaus** [comment] 2021-05-18 05:08
Duplicate of #625

**Closed by marcorennmaus** 2021-05-18 05:08 UTC
