### ISSUE TITLE
Wrong Dates!

### ISSUE THREAD

**Issue by raunakraj122** [top-gg/issues#529] opened 2020-12-16 06:43 UTC
#### Steps to Reproduce

1. Open top.gg
2. Send a comment on the bot page
3. Wait for 5 days (to see "Posted 5 days ago")
4. Reply to the Comment!
5. Check the reply date

#### Expected Behavior

> The comment date should be "5 days ago"
> The reply date should be "Just now"

#### Observed Behavior

> The reply date changes into "5 days ago"

#### Applicable Links or Attachments

[Comment Screenshot](https://media.discordapp.net/attachments/755031719811481601/788655865766608916/unknown.png?width=878&height=354)
[Link to my bot page](https://top.gg/bot/763689673620586507)

#### Web Browser and Version

>Microsoft Edge Version 87.0.664.60 (Official build) (64-bit)

#### Operating System and Version

>Windows 10 20H2

#### Screen Resolution

>1920 x 1080

**Comment by Xignotic84** [comment] 2020-12-18 01:39
Duplicate of #465

**Closed by Xignotic84** 2020-12-18 01:39 UTC

**Comment by raunakraj122** [comment] 2020-12-19 14:26
Ohh didn't notice it, thanks tough!

**Comment by raunakrajadh** [comment] 2021-01-14 15:34
> Duplicate of #465

can you please delete this issue, it has stayed in my repository list and it is really annoying me!
