### ISSUE TITLE
Moderator controls on beta

### ISSUE THREAD

**Issue by kkrypt0nn** [top-gg/issues#696] opened 2021-05-18 05:02 UTC
#### Expected Behavior

I should not see the moderator controls.

#### Observed Behavior

I can see and click on moderator controls about accepting or declining a bot.

#### Applicable Links or Attachments

![Screenshot_20210518-065929.png](https://user-images.githubusercontent.com/43011723/118592769-cb685a80-b7a6-11eb-8d2f-035e576e0263.png)

#### Steps to Reproduce

1. Open top.gg
2. Go on any bot page

#### Web Browser and Version

Edge Mobile - Version 46.03.4.5155

#### Operating System and Version

Android 12 Developer Beta

#### Screen Resolution

1080×2280

#### Additional Information/Comments

It might happen on mobile only.

**Comment by marcorennmaus** [comment] 2021-05-18 05:08
Duplicate of #625

**Closed by marcorennmaus** 2021-05-18 05:08 UTC
